// See https://aka.ms/new-console-template for more information

using DTO;
using InterfaceLayer;
using ManagerLayer;
using System.ComponentModel;

List<string> Comments = new List<string>
            {
                "This article helps me a lot!",
                "That news was very interesting!",
                "The content of the article answered all of my questions!",
                "Great insights, very helpful!",
                "This information is exactly what I was looking for!",
                "I found this article very informative!",
                "Amazing write-up, keep it up!",
                "Thanks for sharing such useful information!",
                "The news was very well presented!",
                "This piece cleared up so many doubts I had!",
                "Extremely well-written and informative!",
                "I learned a lot from this article!",
                "Your content always adds value to my day!",
                "Excellent breakdown of the topic!",
                "I appreciate the detailed explanation!",
                "This news was very enlightening!",
                "The article provided a lot of useful information!",
                "Such an interesting read!",
                "I enjoyed reading this article a lot!",
                "This was very helpful and easy to understand!",
                "The news was presented very clearly!",
                "Great job on this article!",
                "This information was very useful!",
                "I always look forward to your articles!",
                "This was a great read!",
                "I appreciate the thoroughness of this article!",
                "The content was very engaging!",
                "I found the news very informative!",
                "This article was very insightful!",
                "Your writing is always so clear and concise!",
                "This news was very well covered!",
                "I found this very helpful, thank you!",
                "Such a well-researched article!",
                "This content was exactly what I needed!",
                "I love the clarity of your writing!",
                "This article provided a lot of valuable information!",
                "The news was very detailed and thorough!",
                "I learned so much from this article!",
                "This was extremely helpful, thanks!",
                "The article was very well structured!",
                "I appreciate the in-depth analysis!",
                "This news piece was very informative!",
                "Excellent article, very helpful!",
                "I found this very enlightening!",
                "This content is very well written!",
                "Thanks for the clear and concise information!",
                "This article answered all my questions!",
                "Great job, very informative!",
                "I really enjoyed this read!",
                "This news was very well explained!",
                "The information in this article was very useful!",
                "Such a great read, very informative!",
                "This article was exactly what I needed!",
                "The news was very well written!",
                "This was very helpful and informative!",
                "Excellent insights, thank you!",
                "This content was very valuable!",
                "I appreciate the clarity of this article!",
                "Very informative, thank you!",
                "I found the article very useful!",
                "Great read, very enlightening!",
                "This news piece was very well done!",
                "I learned a lot from this content!",
                "This article was very helpful!",
                "Thanks for such an informative article!",
                "The content was very well presented!",
                "I enjoyed the article very much!",
                "This news was very well detailed!",
                "The article provided great information!",
                "I found this very insightful!",
                "Such a helpful article, thank you!",
                "This was a very good read!",
                "The news was very informative!",
                "I appreciate the detailed information!",
                "This article helped me understand the topic better!",
                "Great content, very useful!",
                "This news was very clear and concise!",
                "I found the article very helpful!",
                "The information provided was very valuable!",
                "This was a very enlightening read!",
                "The article was very informative!",
                "I appreciate the thorough information!",
                "This content was very helpful, thanks!",
                "Great article, very well written!",
                "This news was very insightful!",
                "The information was very clear and helpful!",
                "This article was very beneficial!",
                "I found the content very useful!",
                "Such a great article, very informative!",
                "The news was very detailed and helpful!",
                "This was very informative and useful!",
                "Great job on this content!",
                "This article answered all my questions!",
                "The news was very well structured!",
                "I learned a lot from this article!",
                "This content was very engaging!",
                "The article provided a lot of useful information!",
                "This news was very well presented!",
                "I appreciate the detailed explanation!",
                "This was a very helpful article!",
                "The content was very informative!",
                "Great read, very helpful!",
                "The article was very clear and concise!",
                "This news was very valuable!",
                "I found this article very insightful!",
                "The information was very well explained!",
                "This article was very useful, thank you!",
                "The news was very informative and helpful!",
                "This was a very good article!",
                "The content provided a lot of valuable information!",
                "Great job on the article, very informative!",
                "This news was very well written and informative!",
                "I found the article very enlightening!",
                "The information was very useful and clear!",
                "This article was very beneficial, thank you!",
                "The news was very detailed and informative!",
                "I appreciate the clarity and detail of this article!",
                "Great read, very informative and helpful!",
                "This article provided a lot of useful information!",
                "The news was very well structured and informative!",
                "I found the content very engaging and useful!",
                "The article was very clear and helpful!",
                "This news was very well presented and insightful!",
                "Great job on this informative article!",
                "This content was very useful and clear!",
                "The article provided a lot of valuable information!",
                "This news was very helpful and detailed!",
                "I found this article very engaging and informative!",
                "Great read, very well written and useful!",
                "This article was very helpful, thank you!",
                "The news was very detailed and valuable!",
                "This content was very informative and clear!",
                "I appreciate the thoroughness of this article!",
                "The article was very well presented and helpful!",
                "This news was very engaging and informative!",
                "Great job, very useful article!",
                "This content was very clear and informative!",
                "The article provided a lot of useful information!",
                "The news was very well structured and helpful!",
                "I found this article very insightful and valuable!",
                "Great read, very clear and useful!",
                "This article was very engaging and helpful!",
                "The news was very detailed and informative!",
                "This content was very useful, thank you!",
                "I appreciate the thorough information in this article!",
                "The article was very well presented and clear!",
                "This news was very engaging and valuable!",
                "Great job on this clear and informative article!",
                "This content was very well explained and useful!",
                "The article provided a lot of useful information!",
                "The news was very detailed and engaging!",
                "I found this article very helpful and informative!",
                "Great read, very clear and informative!",
                "This article was very beneficial, thank you!",
                "The news was very detailed and valuable!",
                "This content was very well presented and clear!",
                "I appreciate the thoroughness of this article!",
                "The article was very well structured and helpful!",
                "This news was very engaging and informative!",
                "Great job, very useful article!",
                "This content was very clear and informative!",
                "The article provided a lot of useful information!",
                "The news was very well structured and helpful!",
                "I found this article very insightful and valuable!",
                "Great read, very clear and useful!",
                "This article was very engaging and helpful!",
                "The news was very detailed and informative!",
                "This content was very useful, thank you!",
                "I appreciate the thorough information in this article!",
                "The article was very well presented and clear!",
                "This news was very engaging and valuable!",
                "Great job on this clear and informative article!",
                "This content was very well explained and useful!",
                "The article provided a lot of useful information!",
                "The news was very detailed and engaging!",
                "I found this article very helpful and informative!",
                "Great read, very clear and informative!",
                "This article was very beneficial, thank you!",
                "The news was very detailed and valuable!",
                "This content was very well presented and clear!",
                "I appreciate the thoroughness of this article!",
                "The article was very well structured and helpful!",
                "This news was very engaging and informative!",
                "Great job, very useful article!",
                "This content was very clear and informative!",
                "The article provided a lot of useful information!",
                "The news was very well structured and helpful!",
                "I found this article very insightful and valuable!",
                "Great read, very clear and useful!",
                "This article was very engaging and helpful!",
                "The news was very detailed and informative!",
                "This content was very useful, thank you!",
                "I appreciate the thorough information in this article!",
                "The article was very well presented and clear!",
                "This news was very engaging and valuable!",
                "Great job on this clear and informative article!",
                "This content was very well explained and useful!",
                "The article provided a lot of useful information!",
                "The news was very detailed and engaging!",
                "I found this article very helpful and informative!",
                "Great read, very clear and informative!",
                "This article was very beneficial, thank you!",
                "The news was very detailed and valuable!",
                "This content was very well presented and clear!",
                "I appreciate the thoroughness of this article!",
                "The article was very well structured and helpful!",
                "This news was very engaging and informative!",
                "Great job, very useful article!",
                "This content was very clear and informative!",
                "The article provided a lot of useful information!",
                "The news was very well structured and helpful!",
                "I found this article very insightful and valuable!",
                "Great read, very clear and useful!",
                "This article was very engaging and helpful!",
                "The news was very detailed and informative!",
                "This content was very useful, thank you!",
                "I appreciate the thorough information in this article!",
                "The article was very well presented and clear!",
                "This news was very engaging and valuable!",
                "Great job on this clear and informative article!",
                "This content was very well explained and useful!",
                "The article provided a lot of useful information!",
                "The news was very detailed and engaging!",
                "I found this article very helpful and informative!",
                "Great read, very clear and informative!",
                "This article was very beneficial, thank you!",
                "The news was very detailed and valuable!",
                "This content was very well presented and clear!",
                "I appreciate the thoroughness of this article!",
                "The article was very well structured and helpful!",
                "This news was very engaging and informative!",
                "Great job, very useful article!",
                "This content was very clear and informative!",
                "The article provided a lot of useful information!",
                "The news was very well structured and helpful!",
                "I found this article very insightful and valuable!",
                "Great read, very clear and useful!",
                "This article was very engaging and helpful!",
                "The news was very detailed and informative!",
                "This content was very useful, thank you!",
                "I appreciate the thorough information in this article!",
                "The article was very well presented and clear!",
                "This news was very engaging and valuable!",
                "Great job on this clear and informative article!",
                "This content was very well explained and useful!",
                "The article provided a lot of useful information!",
                "The news was very detailed and engaging!",
                "I found this article very helpful and informative!",
                "Great read, very clear and informative!",
                "This article was very beneficial, thank you!",
                "The news was very detailed and valuable!",
                "This content was very well presented and clear!",
                "I appreciate the thoroughness of this article!",
                "The article was very well structured and helpful!",
                "This news was very engaging and informative!",
                "Great job, very useful article!",
                "This content was very clear and informative!",
                "The article provided a lot of useful information!",
                "The news was very well structured and helpful!",
                "I found this article very insightful and valuable!",
                "Great read, very clear and useful!",
                "This article was very engaging and helpful!",
                "The news was very detailed and informative!",
                "This content was very useful, thank you!",
                "I appreciate the thorough information in this article!",
                "The article was very well presented and clear!",
                "This news was very engaging and valuable!",
                "Great job on this clear and informative article!",
                "This content was very well explained and useful!",
                "The article provided a lot of useful information!",
                "The news was very detailed and engaging!",
                "I found this article very helpful and informative!",
                "Great read, very clear and informative!",
                "This article was very beneficial, thank you!",
                "The news was very detailed and valuable!",
                "This content was very well presented and clear!",
                "I appreciate the thoroughness of this article!",
                "The article was very well structured and helpful!",
                "This news was very engaging and informative!",
                "Great job, very useful article!",
                "This content was very clear and informative!",
                "The article provided a lot of useful information!",
                "The news was very well structured and helpful!",
                "I found this article very insightful and valuable!",
                "Great read, very clear and useful!",
                "This article was very engaging and helpful!",
                "The news was very detailed and informative!",
                "This content was very useful, thank you!",
                "I appreciate the thorough information in this article!",
                "The article was very well presented and clear!",
                "This news was very engaging and valuable!",
                "Great job on this clear and informative article!",
                "This content was very well explained and useful!",
                "The article provided a lot of useful information!",
                "The news was very detailed and engaging!",
                "I found this article very helpful and informative!",
                "Great read, very clear and informative!",
                "This article was very beneficial, thank you!",
                "The news was very detailed and valuable!",
                "This content was very well presented and clear!",
                "I appreciate the thoroughness of this article!",
                "The article was very well structured and helpful!",
                "This news was very engaging and informative!",
                "Great job, very useful article!",
                "This content was very clear and informative!",
                "The article provided a lot of useful information!",
                "The news was very well structured and helpful!",
                "I found this article very insightful and valuable!",
                "Great read, very clear and useful!",
                "This article was very engaging and helpful!",
                "The news was very detailed and informative!",
                "This content was very useful, thank you!",
                "I appreciate the thorough information in this article!",
                "The article was very well presented and clear!",
                "This news was very engaging and valuable!",
                "Great job on this clear and informative article!",
                "This content was very well explained and useful!",
                "The article provided a lot of useful information!",
                "The news was very detailed and engaging!",
                "I found this article very helpful and informative!",
                "Great read, very clear and informative!",
                "This article was very beneficial, thank you!",
                "The news was very detailed and valuable!",
                "This content was very well presented and clear!",
                "I appreciate the thoroughness of this article!",
                "The article was very well structured and helpful!",
                "This news was very engaging and informative!",
                "Great job, very useful article!",
                "This content was very clear and informative!",
                "The article provided a lot of useful information!",
                "The news was very well structured and helpful!",
                "I found this article very insightful and valuable!",
                "Great read, very clear and useful!",
                "This article was very engaging and helpful!",
                "The news was very detailed and informative!",
                "This content was very useful, thank you!",
                "I appreciate the thorough information in this article!",
                "The article was very well presented and clear!",
                "This news was very engaging and valuable!",
                "Great job on this clear and informative article!",
                "This content was very well explained and useful!",
                "The article provided a lot of useful information!",
                "The news was very detailed and engaging!",
                "I found this article very helpful and informative!",
                "Great read, very clear and informative!",
                "This article was very beneficial, thank you!",
                "The news was very detailed and valuable!",
                "This content was very well presented and clear!",
                "I appreciate the thoroughness of this article!",
                "The article was very well structured and helpful!",
                "This news was very engaging and informative!",
                "Great job, very useful article!",
                "This content was very clear and informative!",
                "The article provided a lot of useful information!",
                "The news was very well structured and helpful!",
                "I found this article very insightful and valuable!",
                "Great read, very clear and useful!",
                "This article was very engaging and helpful!",
                "The news was very detailed and informative!",
                "This content was very useful, thank you!",
                "I appreciate the thorough information in this article!",
                "The article was very well presented and clear!",
                "This news was very engaging and valuable!",
                "Great job on this clear and informative article!",
                "This content was very well explained and useful!",
                "The article provided a lot of useful information!",
                "The news was very detailed and engaging!",
                "I found this article very helpful and informative!",
                "Great read, very clear and informative!",
                "This article was very beneficial, thank you!",
                "The news was very detailed and valuable!",
                "This content was very well presented and clear!",
                "I appreciate the thoroughness of this article!",
                "The article was very well structured and helpful!",
                "This news was very engaging and informative!",
                "Great job, very useful article!",
                "This content was very clear and informative!",
                "The article provided a lot of useful information!",
                "The news was very well structured and helpful!",
                "I found this article very insightful and valuable!",
                "Great read, very clear and useful!",
                "This article was very engaging and helpful!",
                "The news was very detailed and informative!",
                "This content was very useful, thank you!",
                "I appreciate the thorough information in this article!",
                "The article was very well presented and clear!",
                "This news was very engaging and valuable!",
                "Great job on this clear and informative article!",
                "This content was very well explained and useful!",
                "The article provided a lot of useful information!",
                "The news was very detailed and engaging!",
                "I found this article very helpful and informative!",
                "Great read, very clear and informative!",
                "This article was very beneficial, thank you!",
                "The news was very detailed and valuable!",
                "This content was very well presented and clear!",
                "I appreciate the thoroughness of this article!",
                "The article was very well structured and helpful!",
                "This news was very engaging and informative!",
                "Great job, very useful article!",
                "This content was very clear and informative!",
                "The article provided a lot of useful information!",
                "The news was very well structured and helpful!",
                "I found this article very insightful and valuable!",
                "Great read, very clear and useful!",
                "This article was very engaging and helpful!",
                "The news was very detailed and informative!",
                "This content was very useful, thank you!",
                "I appreciate the thorough information in this article!",
                "The article was very well presented and clear!",
                "This news was very engaging and valuable!",
                "Great job on this clear and informative article!",
                "This content was very well explained and useful!",
                "The article provided a lot of useful information!",
                "The news was very detailed and engaging!",
                "I found this article very helpful and informative!",
                "Great read, very clear and informative!",
                "This article was very beneficial, thank you!",
                "The news was very detailed and valuable!",
                "This content was very well presented and clear!",
                "I appreciate the thoroughness of this article!",
                "The article was very well structured and helpful!",
                "This news was very engaging and informative!",
                "Great job, very useful article!",
                "This content was very clear and informative!",
                "The article provided a lot of useful information!",
                "The news was very well structured and helpful!",
                "I found this article very insightful and valuable!",
                "Great read, very clear and useful!",
                "This article was very engaging and helpful!",
                "The news was very detailed and informative!",
                "This content was very useful, thank you!",
                "I appreciate the thorough information in this article!",
                "The article was very well presented and clear!",
                "This news was very engaging and valuable!",
                "Great job on this clear and informative article!",
                "This content was very well explained and useful!",
                "The article provided a lot of useful information!",
                "The news was very detailed and engaging!",
                "I found this article very helpful and informative!",
                "Great read, very clear and informative!",
                "This article was very beneficial, thank you!",
                "The news was very detailed and valuable!",
                "This content was very well presented and clear!",
                "I appreciate the thoroughness of this article!",
                "The article was very well structured and helpful!",
                "This news was very engaging and informative!",
                "Great job, very useful article!",
                "This content was very clear and informative!",
                "The article provided a lot of useful information!",
                "The news was very well structured and helpful!",
                "I found this article very insightful and valuable!",
                "Great read, very clear and useful!",
                "This article was very engaging and helpful!",
                "The news was very detailed and informative!",
                "This content was very useful, thank you!",
                "I appreciate the thorough information in this article!",
                "The article was very well presented and clear!",
                "This news was very engaging and valuable!",
                "Great job on this clear and informative article!",
                "This content was very well explained and useful!",
                "The article provided a lot of useful information!",
                "The news was very detailed and engaging!",
                "I found this article very helpful and informative!",
                "Great read, very clear and informative!",
                "This article was very beneficial, thank you!",
                "The news was very detailed and valuable!",
                "This content was very well presented and clear!",
                "I appreciate the thoroughness of this article!",
                "The article was very well structured and helpful!",
                "This news was very engaging and informative!",
                "Great job, very useful article!",
                "This content was very clear and informative!",
                "The article provided a lot of useful information!",
                "The news was very well structured and helpful!",
                "I found this article very insightful and valuable!",
                "Great read, very clear and useful!",
                "This article was very engaging and helpful!",
                "The news was very detailed and informative!",
                "This content was very useful, thank you!",
                "I appreciate the thorough information in this article!",
                "The article was very well presented and clear!",
                "This news was very engaging and valuable!",
                "Great job on this clear and informative article!",
                "This content was very well explained and useful!",
                "The article provided a lot of useful information!",
                "The news was very detailed and engaging!",
                "I found this article very helpful and informative!",
                "Great read, very clear and informative!",
                "This article was very beneficial, thank you!",
                "The news was very detailed and valuable!",
                "This content was very well presented and clear!",
                "I appreciate the thoroughness of this article!",
                "The article was very well structured and helpful!",
                "This news was very engaging and informative!",
                "Great job, very useful article!",
                "This content was very clear and informative!",
                "The article provided a lot of useful information!",
                "The news was very well structured and helpful!",
                "I found this article very insightful and valuable!",
                "Great read, very clear and useful!",
                "This article was very engaging and helpful!",
                "The news was very detailed and informative!",
                "This content was very useful, thank you!",
                "I appreciate the thorough information in this article!",
                "The article was very well presented and clear!",
                "This news was very engaging and valuable!",
                "Great job on this clear and informative article!",
                "This content was very well explained and useful!",
                "The article provided a lot of useful information!",
                "The news was very detailed and engaging!",
                "I found this article very helpful and informative!",
                "Great read, very clear and informative!",
                "This article was very beneficial, thank you!",
                "The news was very detailed and valuable!",
                "This content was very well presented and clear!",
                "I appreciate the thoroughness of this article!",
                "The article was very well structured and helpful!",
                "This news was very engaging and informative!",
                "Great job, very useful article!",
                "This content was very clear and informative!",
                "The article provided a lot of useful information!",
                "The news was very well structured and helpful!",
                "I found this article very insightful and valuable!",
                "Great read, very clear and useful!",
                "This article was very engaging and helpful!",
                "The news was very detailed and informative!",
                "This content was very useful, thank you!",
                "I appreciate the thorough information in this article!",
                "The article was very well presented and clear!",
                "This news was very engaging and valuable!",
                "Great job on this clear and informative article!",
                "This content was very well explained and useful!",
                "The article provided a lot of useful information!",
                "The news was very detailed and engaging!",
                "I found this article very helpful and informative!",
                "Great read, very clear and informative!",
                "This article was very beneficial, thank you!",
                "The news was very detailed and valuable!",
                "This content was very well presented and clear!",
                "I appreciate the thoroughness of this article!",
                "The article was very well structured and helpful!",
                "This news was very engaging and informative!",
                "Great job, very useful article!",
                "This content was very clear and informative!",
                "The article provided a lot of useful information!",
                "The news was very well structured and helpful!",
                "I found this article very insightful and valuable!",
                "Great read, very clear and useful!",
                "This article was very engaging and helpful!",
                "The news was very detailed and informative!",
                "This content was very useful, thank you!",
                "I appreciate the thorough information in this article!",
                "The article was very well presented and clear!",
                "This news was very engaging and valuable!",
                "Great job on this clear and informative article!",
                "This content was very well explained and useful!",
                "The article provided a lot of useful information!",
                "The news was very detailed and engaging!",
                "I found this article very helpful and informative!",
                "Great read, very clear and informative!",
                "This article was very beneficial, thank you!",
                "The news was very detailed and valuable!",
                "This content was very well presented and clear!",
                "I appreciate the thoroughness of this article!",
                "The article was very well structured and helpful!",
                "This news was very engaging and informative!",
                "Great job, very useful article!",
                "This content was very clear and informative!",
                "The article provided a lot of useful information!",
                "The news was very well structured and helpful!",
                "I found this article very insightful and valuable!",
                "Great read, very clear and useful!",
                "This article was very engaging and helpful!",
                "The news was very detailed and informative!",
                "This content was very useful, thank you!",
                "I appreciate the thorough information in this article!",
                "The article was very well presented and clear!",
                "This news was very engaging and valuable!",
                "Great job on this clear and informative article!",
                "This content was very well explained and useful!",
                "The article provided a lot of useful information!",
                "The news was very detailed and engaging!",
                "I found this article very helpful and informative!",
                "Great read, very clear and informative!",
                "This article was very beneficial, thank you!",
                "The news was very detailed and valuable!",
                "This content was very well presented and clear!",
                "I appreciate the thoroughness of this article!",
                "The article was very well structured and helpful!",
                "This news was very engaging and informative!",
                "Great job, very useful article!",
                "This content was very clear and informative!",
                "The article provided a lot of useful information!",
                "The news was very well structured and helpful!",
                "I found this article very insightful and valuable!",
                "Great read, very clear and useful!",
                "This article was very engaging and helpful!",
                "The news was very detailed and informative!",
                "This content was very useful, thank you!",
                "I appreciate the thorough information in this article!",
                "The article was very well presented and clear!",
                "This news was very engaging and valuable!",
                "Great job on this clear and informative article!",
                "This content was very well explained and useful!",
                "The article provided a lot of useful information!",
                "The news was very detailed and engaging!",
                "I found this article very helpful and informative!",
                "Great read, very clear and informative!",
                "This article was very beneficial, thank you!",
                "The news was very detailed and valuable!",
                "This content was very well presented and clear!",
                "I appreciate the thoroughness of this article!",
                "The article was very well structured and helpful!",
                "This news was very engaging and informative!",
                "Great job, very useful article!",
                "This content was very clear and informative!",
                "The article provided a lot of useful information!",
                "The news was very well structured and helpful!",
                "I found this article very insightful and valuable!",
                "Great read, very clear and useful!",
                "This article was very engaging and helpful!",
                "The news was very detailed and informative!",
                "This content was very useful, thank you!",
                "I appreciate the thorough information in this article!",
                "The article was very well presented and clear!",
                "This news was very engaging and valuable!",
                "Great job on this clear and informative article!",
                "This content was very well explained and useful!",
                "The article provided a lot of useful information!",
                "The news was very detailed and engaging!",
                "I found this article very helpful and informative!",
                "Great read, very clear and informative!",
                "This article was very beneficial, thank you!",
                "The news was very detailed and valuable!",
                "This content was very well presented and clear!",
                "I appreciate the thoroughness of this article!",
                "The article was very well structured and helpful!",
                "This news was very engaging and informative!",
                "Great job, very useful article!",
                "This content was very clear and informative!",
                "The article provided a lot of useful information!",
                "The news was very well structured and helpful!",
                "I found this article very insightful and valuable!",
                "Great read, very clear and useful!",
                "This article was very engaging and helpful!",
                "The news was very detailed and informative!",
                "This content was very useful, thank you!",
                "I appreciate the thorough information in this article!",
                "The article was very well presented and clear!",
                "This news was very engaging and valuable!",
                "Great job on this clear and informative article!",
                "This content was very well explained and useful!",
                "The article provided a lot of useful information!",
                "The news was very detailed and engaging!",
                "I found this article very helpful and informative!",
                "Great read, very clear and informative!",
                "This article was very beneficial, thank you!",
                "The news was very detailed and valuable!",
                "This content was very well presented and clear!",
                "I appreciate the thoroughness of this article!",
                "The article was very well structured and helpful!",
                "This news was very engaging and informative!",
                "Great job, very useful article!",
                "This content was very clear and informative!",
                "The article provided a lot of useful information!",
                "The news was very well structured and helpful!",
                "I found this article very insightful and valuable!",
                "Great read, very clear and useful!",
                "This article was very engaging and helpful!",
                "The news was very detailed and informative!",
                "This content was very useful, thank you!",
                "I appreciate the thorough information in this article!",
                "The article was very well presented and clear!",
                "This news was very engaging and valuable!",
                "Great job on this clear and informative article!",
                "This content was very well explained and useful!",
                "The article provided a lot of useful information!",
                "The news was very detailed and engaging!",
                "I found this article very helpful and informative!",
                "Great read, very clear and informative!",
                "This article was very beneficial, thank you!",
                "The news was very detailed and valuable!",
                "This content was very well presented and clear!",
                "I appreciate the thoroughness of this article!",
                "The article was very well structured and helpful!",
                "This news was very engaging and informative!",
                "Great job, very useful article!",
                "This content was very clear and informative!",
                "The article provided a lot of useful information!",
                "The news was very well structured and helpful!",
                "I found this article very insightful and valuable!",
                "Great read, very clear and useful!",
                "This article was very engaging and helpful!",
                "The news was very detailed and informative!",
                "This content was very useful, thank you!",
                "I appreciate the thorough information in this article!",
                "The article was very well presented and clear!",
                "This news was very engaging and valuable!",
                "Great job on this clear and informative article!",
                "This content was very well explained and useful!",
                "The article provided a lot of useful information!",
                "The news was very detailed and engaging!",
                "I found this article very helpful and informative!",
                "Great read, very clear and informative!",
                "This article was very beneficial, thank you!",
                "The news was very detailed and valuable!",
                "This content was very well presented and clear!",
                "I appreciate the thoroughness of this article!",
                "The article was very well structured and helpful!",
                "This news was very engaging and informative!",
                "Great job, very useful article!",
                "This content was very clear and informative!",
                "The article provided a lot of useful information!",
                "The news was very well structured and helpful!",
                "I found this article very insightful and valuable!",
                "Great read, very clear and useful!",
                "This article was very engaging and helpful!",
                "The news was very detailed and informative!",
                "This content was very useful, thank you!",
                "I appreciate the thorough information in this article!",
                "The article was very well presented and clear!",
                "This news was very engaging and valuable!",
                "Great job on this clear and informative article!",
                "This content was very well explained and useful!",
                "The article provided a lot of useful information!",
                "The news was very detailed and engaging!",
                "I found this article very helpful and informative!",
                "Great read, very clear and informative!",
                "This article was very beneficial, thank you!",
                "The news was very detailed and valuable!",
                "This content was very well presented and clear!",
                "I appreciate the thoroughness of this article!",
                "The article was very well structured and helpful!",
                "This news was very engaging and informative!",
                "Great job, very useful article!",
                "This content was very clear and informative!",
                "The article provided a lot of useful information!",
                "The news was very well structured and helpful!",
                "I found this article very insightful and valuable!",
                "Great read, very clear and useful!",
                "This article was very engaging and helpful!",
                "The news was very detailed and informative!",
                "This content was very useful, thank you!",
                "I appreciate the thorough information in this article!",
                "The article was very well presented and clear!",
                "This news was very engaging and valuable!",
                "Great job on this clear and informative article!",
                "This content was very well explained and useful!",
                "The article provided a lot of useful information!",
                "The news was very detailed and engaging!",
                "I found this article very helpful and informative!",
                "Great read, very clear and informative!",
                "This article was very beneficial, thank you!",
                "The news was very detailed and valuable!",
                "This content was very well presented and clear!",
                "I appreciate the thoroughness of this article!",
                "The article was very well structured and helpful!",
                "This news was very engaging and informative!",
                "Great job, very useful article!",
                "This content was very clear and informative!",
                "The article provided a lot of useful information!",
                "The news was very well structured and helpful!",
                "I found this article very insightful and valuable!",
                "Great read, very clear and useful!",
                "This article was very engaging and helpful!",
                "The news was very detailed and informative!",
                "This content was very useful, thank you!",
                "I appreciate the thorough information in this article!",
                "The article was very well presented and clear!",
                "This news was very engaging and valuable!",
                "Great job on this clear and informative article!",
                "This content was very well explained and useful!",
                "The article provided a lot of useful information!",
                "The news was very detailed and engaging!",
                "I found this article very helpful and informative!",
                "Great read, very clear and informative!",
                "This article was very beneficial, thank you!",
                "The news was very detailed and valuable!",
                "This content was very well presented and clear!",
                "I appreciate the thoroughness of this article!",
                "The article was very well structured and helpful!",
                "This news was very engaging and informative!",
                "Great job, very useful article!",
                "This content was very clear and informative!",
                "The article provided a lot of useful information!",
                "The news was very well structured and helpful!",
                "I found this article very insightful and valuable!",
                "Great read, very clear and useful!",
                "This article was very engaging and helpful!",
                "The news was very detailed and informative!",
                "This content was very useful, thank you!",
                "I appreciate the thorough information in this article!",
                "The article was very well presented and clear!",
                "This news was very engaging and valuable!",
                "Great job on this clear and informative article!",
                "This content was very well explained and useful!",
                "The article provided a lot of useful information!",
                "The news was very detailed and engaging!",
                "I found this article very helpful and informative!",
                "Great read, very clear and informative!",
                "This article was very beneficial, thank you!",
                "The news was very detailed and valuable!",
                "This content was very well presented and clear!",
                "I appreciate the thoroughness of this article!",
                "The article was very well structured and helpful!",
                "This news was very engaging and informative!",
                "Great job, very useful article!",
                "This content was very clear and informative!",
                "The article provided a lot of useful information!",
                "The news was very well structured and helpful!",
                "I found this article very insightful and valuable!",
                "Great read, very clear and useful!",
                "This article was very engaging and helpful!",
                "The news was very detailed and informative!",
                "This content was very useful, thank you!",
                "I appreciate the thorough information in this article!",
                "The article was very well presented and clear!",
                "This news was very engaging and valuable!",
                "Great job on this clear and informative article!",
                "This content was very well explained and useful!",
                "The article provided a lot of useful information!",
                "The news was very detailed and engaging!",
                "I found this article very helpful and informative!",
                "Great read, very clear and informative!",
                "This article was very beneficial, thank you!",
                "The news was very detailed and valuable!",
                "This content was very well presented and clear!",
                "I appreciate the thoroughness of this article!",
                "The article was very well structured and helpful!",
                "This news was very engaging and informative!",
                "Great job, very useful article!",
                "This content was very clear and informative!",
                "The article provided a lot of useful information!",
                "The news was very well structured and helpful!",
                "I found this article very insightful and valuable!",
                "Great read, very clear and useful!",
                "This article was very engaging and helpful!",
                "The news was very detailed and informative!",
                "This content was very useful, thank you!",
                "I appreciate the thorough information in this article!",
                "The article was very well presented and clear!",
                "This news was very engaging and valuable!",
                "Great job on this clear and informative article!",
                "This content was very well explained and useful!",
                "The article provided a lot of useful information!",
                "The news was very detailed and engaging!",
                "I found this article very helpful and informative!",
                "Great read, very clear and informative!",
                "This article was very beneficial, thank you!",
                "The news was very detailed and valuable!",
                "This content was very well presented and clear!",
                "I appreciate the thoroughness of this article!",
                "The article was very well structured and helpful!",
                "This news was very engaging and informative!",
                "Great job, very useful article!",
                "This content was very clear and informative!",
                "The article provided a lot of useful information!",
                "The news was very well structured and helpful!",
                "I found this article very insightful and valuable!",
                "Great read, very clear and useful!",
                "This article was very engaging and helpful!",
                "The news was very detailed and informative!",
                "This content was very useful, thank you!",
                "I appreciate the thorough information in this article!",
                "The article was very well presented and clear!",
                "This news was very engaging and valuable!",
                "Great job on this clear and informative article!",
                "This content was very well explained and useful!",
                "The article provided a lot of useful information!",
                "The news was very detailed and engaging!",
                "I found this article very helpful and informative!",
                "Great read, very clear and informative!",
                "This article was very beneficial, thank you!",
                "The news was very detailed and valuable!",
                "This content was very well presented and clear!",
                "I appreciate the thoroughness of this article!",
                "The article was very well structured and helpful!",
                "This news was very engaging and informative!",
                "Great job, very useful article!",
                "This content was very clear and informative!",
                "The article provided a lot of useful information!",
                "The news was very well structured and helpful!",
                "I found this article very insightful and valuable!",
                "Great read, very clear and useful!",
                "This article was very engaging and helpful!",
                "The news was very detailed and informative!",
                "This content was very useful, thank you!",
                "I appreciate the thorough information in this article!",
                "The article was very well presented and clear!",
                "This news was very engaging and valuable!",
                "Great job on this clear and informative article!",
                "This content was very well explained and useful!",
                "The article provided a lot of useful information!",
                "The news was very detailed and engaging!",
                "I found this article very helpful and informative!",
                "Great read, very clear and informative!",
                "This article was very beneficial, thank you!",
                "The news was very detailed and valuable!",
                "This content was very well presented and clear!",
                "I appreciate the thoroughness of this article!",
                "The article was very well structured and helpful!",
                "This news was very engaging and informative!",
                "Great job, very useful article!",
                "This content was very clear and informative!",
                "The article provided a lot of useful information!",
                "The news was very well structured and helpful!",
                "I found this article very insightful and valuable!",
                "Great read, very clear and useful!",
                "This article was very engaging and helpful!",
                "The news was very detailed and informative!",
                "This content was very useful, thank you!",
                "I appreciate the thorough information in this article!",
                "The article was very well presented and clear!",
                "This news was very engaging and valuable!",
                "Great job on this clear and informative article!",
                "This content was very well explained and useful!",
                "The article provided a lot of useful information!",
                "The news was very detailed and engaging!",
                "I found this article very helpful and informative!",
                "Great read, very clear and informative!",
                "This article was very beneficial, thank you!",
                "The news was very detailed and valuable!",
                "This content was very well presented and clear!",
                "I appreciate the thoroughness of this article!",
                "The article was very well structured and helpful!",
                "This news was very engaging and informative!",
                "Great job, very useful article!",
                "This content was very clear and informative!",
                "The article provided a lot of useful information!",
                "The news was very well structured and helpful!",
                "I found this article very insightful and valuable!",
                "Great read, very clear and useful!",
                "This article was very engaging and helpful!",
                "The news was very detailed and informative!",
                "This content was very useful, thank you!",
                "I appreciate the thorough information in this article!",
                "The article was very well presented and clear!",
                "This news was very engaging and valuable!",
                "Great job on this clear and informative article!",
                "This content was very well explained and useful!",
                "The article provided a lot of useful information!",
                "The news was very detailed and engaging!",
                "I found this article very helpful and informative!",
                "Great read, very clear and informative!",
                "This article was very beneficial, thank you!",
                "The news was very detailed and valuable!",
                "This content was very well presented and clear!",
                "I appreciate the thoroughness of this article!",
                "The article was very well structured and helpful!",
                "This news was very engaging and informative!",
                "Great job, very useful article!",
                "This content was very clear and informative!",
                "The article provided a lot of useful information!",
                "The news was very well structured and helpful!",
                "I found this article very insightful and valuable!",
                "Great read, very clear and useful!",
                "This article was very engaging and helpful!",
                "The news was very detailed and informative!",
                "This content was very useful, thank you!",
                "I appreciate the thorough information in this article!",
                "The article was very well presented and clear!",
                "This news was very engaging and valuable!",
                "Great job on this clear and informative article!",
                "This content was very well explained and useful!",
                "The article provided a lot of useful information!",
                "The news was very detailed and engaging!",
                "I found this article very helpful and informative!",
                "Great read, very clear and informative!",
                "This article was very beneficial, thank you!",
                "The news was very detailed and valuable!",
                "This content was very well presented and clear!",
                "I appreciate the thoroughness of this article!",
                "The article was very well structured and helpful!",
                "This news was very engaging and informative!",
                "Great job, very useful article!",
                "This content was very clear and informative!",
                "The article provided a lot of useful information!",
                "The news was very well structured and helpful!",
                "I found this article very insightful and valuable!",
                "Great read, very clear and useful!",
                "This article was very engaging and helpful!",
                "The news was very detailed and informative!",
                "This content was very useful, thank you!",
                "I appreciate the thorough information in this article!",
                "The article was very well presented and clear!",
                "This news was very engaging and valuable!",
                "Great job on this clear and informative article!",
                "This content was very well explained and useful!",
                "The article provided a lot of useful information!",
                "The news was very detailed and engaging!",
                "I found this article very helpful and informative!",
                "Great read, very clear and informative!",
                "This article was very beneficial, thank you!",
                "The news was very detailed and valuable!",
                "This content was very well presented and clear!",
                "I appreciate the thoroughness of this article!",
                "The article was very well structured and helpful!",
                "This news was very engaging and informative!",
                "Great job, very useful article!",
                "This content was very clear and informative!",
                "The article provided a lot of useful information!",
                "The news was very well structured and helpful!",
                "I found this article very insightful and valuable!",
                "Great read, very clear and useful!",
                "This article was very engaging and helpful!",
                "The news was very detailed and informative!",
                "This content was very useful, thank you!",
                "I appreciate the thorough information in this article!",
                "The article was very well presented and clear!",
                "This news was very engaging and valuable!",
                "Great job on this clear and informative article!",
                "This content was very well explained and useful!",
                "The article provided a lot of useful information!",
                "The news was very detailed and engaging!",
                "I found this article very helpful and informative!",
                "Great read, very clear and informative!",
                "This article was very beneficial, thank you!",
                "The news was very detailed and valuable!",
                "This content was very well presented and clear!",
                "I appreciate the thoroughness of this article!",
                "The article was very well structured and helpful!",
                "This news was very engaging and informative!",
                "Great job, very useful article!",
                "This content was very clear and informative!",
                "The article provided a lot of useful information!",
                "The news was very well structured and helpful!",
                "I found this article very insightful and valuable!",
                "Great read, very clear and useful!",
                "This article was very engaging and helpful!",
                "The news was very detailed and informative!",
                "This content was very useful, thank you!",
                "I appreciate the thorough information in this article!",
                "The article was very well presented and clear!",
                "This news was very engaging and valuable!",
                "Great job on this clear and informative article!",
                "This content was very well explained and useful!",
                "The article provided a lot of useful information!",
                "The news was very detailed and engaging!",
                "I found this article very helpful and informative!",
                "Great read, very clear and informative!",
                "This article was very beneficial, thank you!",
                "The news was very detailed and valuable!",
                "This content was very well presented and clear!",
                "I appreciate the thoroughness of this article!",
                "The article was very well structured and helpful!",
                "This news was very engaging and informative!",
                "Great job, very useful article!",
                "This content was very clear and informative!",
                "The article provided a lot of useful information!",
                "The news was very well structured and helpful!",
                "I found this article very insightful and valuable!",
                "Great read, very clear and useful!",
                "This article was very engaging and helpful!",
                "The news was very detailed and informative!",
                "This content was very useful, thank you!",
                "I appreciate the thorough information in this article!",
                "The article was very well presented and clear!",
                "This news was very engaging and valuable!",
                "Great job on this clear and informative article!",
                "This content was very well explained and useful!",
                "The article provided a lot of useful information!",
                "The news was very detailed and engaging!",
                "I found this article very helpful and informative!",
                "Great read, very clear and informative!",
                "This article was very beneficial, thank you!",
                "The news was very detailed and valuable!",
                "This content was very well presented and clear!",
                "I appreciate the thoroughness of this article!",
                "The article was very well structured and helpful!",
                "This news was very engaging and informative!",
                "Great job, very useful article!",
                "This content was very clear and informative!",
                "The article provided a lot of useful information!",
                "The news was very well structured and helpful!",
                "I found this article very insightful and valuable!",
                "Great read, very clear and useful!",
                "This article was very engaging and helpful!",
                "The news was very detailed and informative!",
                "This content was very useful, thank you!",
                "I appreciate the thorough information in this article!",
                "The article was very well presented and clear!",
                "This news was very engaging and valuable!",
                "Great job on this clear and informative article!",
                "This content was very well explained and useful!",
                "The article provided a lot of useful information!",
                "The news was very detailed and engaging!",
                "I found this article very helpful and informative!",
                "Great read, very clear and informative!",
                "This article was very beneficial, thank you!",
                "The news was very detailed and valuable!",
                "This content was very well presented and clear!",
                "I appreciate the thoroughness of this article!",
                "The article was very well structured and helpful!",
                "This news was very engaging and informative!",
                "Great job, very useful article!",
                "This content was very clear and informative!",
                "The article provided a lot of useful information!",
                "The news was very well structured and helpful!",
                "I found this article very insightful and valuable!",
                "Great read, very clear and useful!",
                "This article was very engaging and helpful!",
                "The news was very detailed and informative!",
                "This content was very useful, thank you!",
                "I appreciate the thorough information in this article!",
                "The article was very well presented and clear!",
                "This news was very engaging and valuable!",
                "Great job on this clear and informative article!",
                "This content was very well explained and useful!",
                "The article provided a lot of useful information!",
                "The news was very detailed and engaging!",
                "I found this article very helpful and informative!",
                "Great read, very clear and informative!",
                "This article was very beneficial, thank you!",
                "The news was very detailed and valuable!",
                "This content was very well presented and clear!",
                "I appreciate the thoroughness of this article!",
                "The article was very well structured and helpful!",
                "This news was very engaging and informative!",
                "Great job, very useful article!",
                "This content was very clear and informative!",
                "The article provided a lot of useful information!",
                "The news was very well structured and helpful!",
                "I found this article very insightful and valuable!",
                "Great read, very clear and useful!",
                "This article was very engaging and helpful!",
                "The news was very detailed and informative!",
                "This content was very useful, thank you!",
                "I appreciate the thorough information in this article!",
                "The article was very well presented and clear!",
                "This news was very engaging and valuable!",
                "Great job on this clear and informative article!",
                "This content was very well explained and useful!",
                "The article provided a lot of useful information!",
                "The news was very detailed and engaging!",
                "I found this article very helpful and informative!",
                "Great read, very clear and informative!",
                "This article was very beneficial, thank you!",
                "The news was very detailed and valuable!",
                "This content was very well presented and clear!",
                "I appreciate the thoroughness of this article!",
                "The article was very well structured and helpful!",
                "This news was very engaging and informative!",
                "Great job, very useful article!",
                "This content was very clear and informative!",
                "The article provided a lot of useful information!",
                "The news was very well structured and helpful!",
                "I found this article very insightful and valuable!",
                "Great read, very clear and useful!",
                "This article was very engaging and helpful!",
                "The news was very detailed and informative!",
                "This content was very useful, thank you!",
                "I appreciate the thorough information in this article!",
                "The article was very well presented and clear!",
                "This news was very engaging and valuable!",
                "Great job on this clear and informative article!",
                "This content was very well explained and useful!",
                "The article provided a lot of useful information!",
                "The news was very detailed and engaging!",
                "I found this article very helpful and informative!",
                "Great read, very clear and informative!",
                "This article was very beneficial, thank you!",
                "The news was very detailed and valuable!",
                "This content was very well presented and clear!",
                "I appreciate the thoroughness of this article!",
                "The article was very well structured and helpful!",
                "This news was very engaging and informative!",
                "Great job, very useful article!",
                "This content was very clear and informative!",
                "The article provided a lot of useful information!",
                "The news was very well structured and helpful!",
                "I found this article very insightful and valuable!",
                "Great read, very clear and useful!",
                "This article was very engaging and helpful!",
                "The news was very detailed and informative!",
                "This content was very useful, thank you!",
                "I appreciate the thorough information in this article!",
                "The article was very well presented and clear!",
                "This news was very engaging and valuable!",
                "Great job on this clear and informative article!",
                "This content was very well explained and useful!",
                "The article provided a lot of useful information!",
                "The news was very detailed and engaging!",
                "I found this article very helpful and informative!",
                "Great read, very clear and informative!",
                "This article was very beneficial, thank you!",
                "The news was very detailed and valuable!",
                "This content was very well presented and clear!",
                "I appreciate the thoroughness of this article!",
                "The article was very well structured and helpful!",
                "This news was very engaging and informative!",
                "Great job, very useful article!",
                "This content was very clear and informative!",
                "The article provided a lot of useful information!",
                "The news was very well structured and helpful!",
                "I found this article very insightful and valuable!",
                "Great read, very clear and useful!",
                "This article was very engaging and helpful!",
                "The news was very detailed and informative!",
                "This content was very useful, thank you!",
                "I appreciate the thorough information in this article!",
                "The article was very well presented and clear!",
                "This news was very engaging and valuable!",
                "Great job on this clear and informative article!",
                "This content was very well explained and useful!",
                "The article provided a lot of useful information!",
                "The news was very detailed and engaging!",
                "I found this article very helpful and informative!",
                "Great read, very clear and informative!",
                "This article was very beneficial, thank you!",
                "The news was very detailed and valuable!",
                "This content was very well presented and clear!",
                "I appreciate the thoroughness of this article!",
                "The article was very well structured and helpful!",
                "This news was very engaging and informative!",
                "Great job, very useful article!",
                "This content was very clear and informative!",
                "The article provided a lot of useful information!",
                "The news was very well structured and helpful!",
                "I found this article very insightful and valuable!",
                "Great read, very clear and useful!",
                "This article was very engaging and helpful!",
                "The news was very detailed and informative!",
                "This content was very useful, thank you!",
                "I appreciate the thorough information in this article!",
                "The article was very well presented and clear!",
                "This news was very engaging and valuable!",
                "Great job on this clear and informative article!",
                "This content was very well explained and useful!",
                "The article provided a lot of useful information!",
                "The news was very detailed and engaging!",
                "I found this article very helpful and informative!",
                "Great read, very clear and informative!",
                "This article was very beneficial, thank you!",
                "The news was very detailed and valuable!",
                "This content was very well presented and clear!",
                "I appreciate the thoroughness of this article!",
                "The article was very well structured and helpful!",
                "This news was very engaging and informative!",
                "Great job, very useful article!",
                "This content was very clear and informative!",
                "The article provided a lot of useful information!",
                "The news was very well structured and helpful!",
                "I found this article very insightful and valuable!",
                "Great read, very clear and useful!",
                "This article was very engaging and helpful!",
                "The news was very detailed and informative!",
                "This content was very useful, thank you!",
                "I appreciate the thorough information in this article!",
                "The article was very well presented and clear!",
                "This news was very engaging and valuable!",
                "Great job on this clear and informative article!",
                "This content was very well explained and useful!",
                "The article provided a lot of useful information!",
                "The news was very detailed and engaging!",
                "I found this article very helpful and informative!",
                "Great read, very clear and informative!",
                "This article was very beneficial, thank you!",
                "The news was very detailed and valuable!",
                "This content was very well presented and clear!",
                "I appreciate the thoroughness of this article!",
                "The article was very well structured and helpful!",
                "This news was very engaging and informative!",
                "Great job, very useful article!",
                "This content was very clear and informative!",
                "The article provided a lot of useful information!",
                "The news was very well structured and helpful!",
                "I found this article very insightful and valuable!",
                "Great read, very clear and useful!",
                "This article was very engaging and helpful!",
                "The news was very detailed and informative!",
                "This content was very useful, thank you!",
                "I appreciate the thorough information in this article!",
                "The article was very well presented and clear!",
                "This news was very engaging and valuable!",
                "Great job on this clear and informative article!",
                "This content was very well explained and useful!",
                "The article provided a lot of useful information!",
                "The news was very detailed and engaging!",
                "I found this article very helpful and informative!",
                "Great read, very clear and informative!",
                "This article was very beneficial, thank you!",
                "The news was very detailed and valuable!",
                "This content was very well presented and clear!",
                "I appreciate the thoroughness of this article!",
                "The article was very well structured and helpful!",
                "This news was very engaging and informative!",
                "Great job, very useful article!",
                "This content was very clear and informative!",
                "The article provided a lot of useful information!",
                "The news was very well structured and helpful!",
                "I found this article very insightful and valuable!",
                "Great read, very clear and useful!",
                "This article was very engaging and helpful!",
                "The news was very detailed and informative!",
                "This content was very useful, thank you!",
                "I appreciate the thorough information in this article!",
                "The article was very well presented and clear!",
                "This news was very engaging and valuable!",
                "Great job on this clear and informative article!",
                "This content was very well explained and useful!",
                "The article provided a lot of useful information!",
                "The news was very detailed and engaging!",
                "I found this article very helpful and informative!",
                "Great read, very clear and informative!",
                "This article was very beneficial, thank you!",
                "The news was very detailed and valuable!",
                "This content was very well presented and clear!",
                "I appreciate the thoroughness of this article!",
                "The article was very well structured and helpful!",
                "This news was very engaging and informative!",
                "Great job, very useful article!",
                "This content was very clear and informative!",
                "The article provided a lot of useful information!",
                "The news was very well structured and helpful!",
                "I found this article very insightful and valuable!",
                "Great read, very clear and useful!",
                "This article was very engaging and helpful!",
                "The news was very detailed and informative!",
                "This content was very useful, thank you!",
                "I appreciate the thorough information in this article!",
                "The article was very well presented and clear!",
                "This news was very engaging and valuable!",
                "Great job on this clear and informative article!",
                "This content was very well explained and useful!",
                "The article provided a lot of useful information!",
                "The news was very detailed and engaging!",
                "I found this article very helpful and informative!",
                "Great read, very clear and informative!",
                "This article was very beneficial, thank you!",
                "The news was very detailed and valuable!",
                "This content was very well presented and clear!",
                "I appreciate the thoroughness of this article!",
                "The article was very well structured and helpful!",
                "This news was very engaging and informative!",
                "Great job, very useful article!",
                "This content was very clear and informative!",
                "The article provided a lot of useful information!",
                "The news was very well structured and helpful!",
                "I found this article very insightful and valuable!",
                "Great read, very clear and useful!",
                "This article was very engaging and helpful!",
                "The news was very detailed and informative!",
                "This content was very useful, thank you!",
                "I appreciate the thorough information in this article!",
                "The article was very well presented and clear!",
                "This news was very engaging and valuable!",
                "Great job on this clear and informative article!",
                "This content was very well explained and useful!",
                "The article provided a lot of useful information!",
                "The news was very detailed and engaging!",
                "I found this article very helpful and informative!",
                "Great read, very clear and informative!",
                "This article was very beneficial, thank you!",
                "The news was very detailed and valuable!",
                "This content was very well presented and clear!",
                "I appreciate the thoroughness of this article!",
                "The article was very well structured and helpful!",
                "This news was very engaging and informative!",
                "Great job, very useful article!",
                "This content was very clear and informative!",
                "The article provided a lot of useful information!",
                "The news was very well structured and helpful!",
                "I found this article very insightful and valuable!",
                "Great read, very clear and useful!",
                "This article was very engaging and helpful!",
                "The news was very detailed and informative!",
                "This content was very useful, thank you!",
                "I appreciate the thorough information in this article!",
                "The article was very well presented and clear!",
                "This news was very engaging and valuable!",
                "Great job on this clear and informative article!",
                "This content was very well explained and useful!",
                "The article provided a lot of useful information!",
                "The news was very detailed and engaging!",
                "I found this article very helpful and informative!",
                "Great read, very clear and informative!",
                "This article was very beneficial, thank you!",
                "The news was very detailed and valuable!",
                "This content was very well presented and clear!",
                "I appreciate the thoroughness of this article!",
                "The article was very well structured and helpful!",
                "This news was very engaging and informative!",
                "Great job, very useful article!",
                "This content was very clear and informative!",
                "The article provided a lot of useful information!",
                "The news was very well structured and helpful!",
                "I found this article very insightful and valuable!",
                "Great read, very clear and useful!",
                "This article was very engaging and helpful!",
                "The news was very detailed and informative!",
                "This content was very useful, thank you!",
                "I appreciate the thorough information in this article!",
                "The article was very well presented and clear!",
                "This news was very engaging and valuable!",
                "Great job on this clear and informative article!",
                "This content was very well explained and useful!",
                "The article provided a lot of useful information!",
                "The news was very detailed and engaging!",
                "I found this article very helpful and informative!",
                "Great read, very clear and informative!",
                "This article was very beneficial, thank you!",
                "The news was very detailed and valuable!",
                "This content was very well presented and clear!",
                "I appreciate the thoroughness of this article!",
                "The article was very well structured and helpful!",
                "This news was very engaging and informative!",
                "Great job, very useful article!",
                "This content was very clear and informative!",
                "The article provided a lot of useful information!",
                "The news was very well structured and helpful!",
                "I found this article very insightful and valuable!",
                "Great read, very clear and useful!",
                "This article was very engaging and helpful!",
                "The news was very detailed and informative!",
                "This content was very useful, thank you!",
                "I appreciate the thorough information in this article!",
                "The article was very well presented and clear!",
                "This news was very engaging and valuable!",
                "Great job on this clear and informative article!",
                "This content was very well explained and useful!",
                "The article provided a lot of useful information!",
                "The news was very detailed and engaging!",
                "I found this article very helpful and informative!",
                "Great read, very clear and informative!",
                "This article was very beneficial, thank you!",
                "The news was very detailed and valuable!",
                "This content was very well presented and clear!",
                "I appreciate the thoroughness of this article!",
                "The article was very well structured and helpful!",
                "This news was very engaging and informative!",
                "Great job, very useful article!",
                "This content was very clear and informative!",
                "The article provided a lot of useful information!",
                "The news was very well structured and helpful!",
                "I found this article very insightful and valuable!",
                "Great read, very clear and useful!",
                "This article was very engaging and helpful!",
                "The news was very detailed and informative!",
                "This content was very useful, thank you!",
                "I appreciate the thorough information in this article!",
                "The article was very well presented and clear!",
                "This news was very engaging and valuable!",
                "Great job on this clear and informative article!",
                "This content was very well explained and useful!",
                "The article provided a lot of useful information!",
                "The news was very detailed and engaging!",
                "I found this article very helpful and informative!",
                "Great read, very clear and informative!",
                "This article was very beneficial, thank you!",
                "The news was very detailed and valuable!",
                "This content was very well presented and clear!",
                "I appreciate the thoroughness of this article!",
                "The article was very well structured and helpful!",
                "This news was very engaging and informative!",
                "Great job, very useful article!",
                "This content was very clear and informative!",
                "The article provided a lot of useful information!",
                "The news was very well structured and helpful!",
                "I found this article very insightful and valuable!",
                "Great read, very clear and useful!",
                "This article was very engaging and helpful!",
                "The news was very detailed and informative"
};

ProjectManager m = new ProjectManager();
IPeopleManager pm = m.PeopleManager;
INewsManager nm = m.NewsManager;
ICommentsManager cm = m.CommentsManager;    
List<UserDTO> users = pm.GetAllUsers().ToList();
List<CarNewsDTO> news = nm.News;




Console.WriteLine("Type Start");
string Start = Console.ReadLine();
if (Start == "Start")
{

    foreach (var n in news)
    {
        while (n.Comments.Count < 400)
        {
            Random randomCom = new Random();
            int randomComments = randomCom.Next(0, Comments.Count - 1);

            Random randomU = new Random();
            int randomUser = randomU.Next(0, users.Count - 1);

            CommentDTO comment = new CommentDTO();
            comment.Content = Comments[randomComments];
            comment.UserId = users[randomUser].Id;
            comment.CommentDate = DateTime.Now;

            await cm.AddCommentAsync(n, comment);
        }
    }


}

Console.WriteLine("done");
Console.ReadLine(); 